### ISSUE TITLE
Image Size in One Batch.

### ISSUE THREAD

**Issue by YusenZhang826** [amazon-research/semimtr-text-recognition#9]
Hello, thanks for your great work. I have some questions about the inputs for the SeqCLR model. Should the images in the same batch have the same size(especially the same width)? Since text in images varies in length, and some images with longer text may be distorted if all images are scaled to the same size. If the padding operation is performed on the image, some frames in the sequence feature will lose their semantics. So how do you preprocess the image size in one batch? 
Looking forward to your response.  Thanks very much!

**Comment by aaberdam** [comment]
Thank you for your interest in our work.

In our implementation: https://github.com/amazon-science/semimtr-text-recognition/blob/d4921a3e36f4ba424e79cf64100515f3bc9c9a0d/semimtr/dataset/dataset.py#L165 we follow a common practice in scene text recognition of resizing the cropped text image to 32x128 pixels, regardless of its original size. Since we don't use padding, we don't have the issue that you mentioned about "null" frames.

I believe that this setting can handle most of the cropped words, especially of the academic datasets. However, it can be sub-optimal for really long words, such as url address. In such cases, you should probably use a different resizing technique to a wider image. That said, for the pretraining stage of SeqCLR the current resizing should be satisfying.

Aviad
